### ISSUE TITLE
Create a way to import/export weights

### ISSUE THREAD

**Issue by dnhandy** [ByteSyncSolutions/Unraveler#3]

**Comment by UICS578** [comment]
Do these two functions in network2.py do what we need?

def load(filename):
    """Load a neural network from the file ``filename``.  Returns an instance of Network.

 def save(self, filename):
        """Save the neural network to the file ``filename``."""

SJ

**Comment by WebCandyLLC** [comment]
I suggest we readapt the weight initializer function to outside the network
objecf. Run it and once it has created a nparray strucfure, use numpy's
dump function I think it is to export to a file or pickle the array to a
file. Then we can add a variable to the network object that when present
tells it load weights from file rather than initializer it as it is doing
now. I can put this together on friday.

Ben

**Comment by UICS578** [comment]
I started this code. How do I get rights to push back to this repository?

user@host:~/PycharmProjects/CS578_Final_Project/Unraveler$ git push
   
   ...

Username for 'https://github.com': UICS578
Password for 'https://UICS578@github.com': 
remote: Permission to ByteSyncSolutions/Unraveler.git denied to UICS578.
fatal: unable to access 'https://github.com/ByteSyncSolutions/Unraveler.git/': The requested URL returned error: 403

**Comment by WebCandyLLC** [comment]
I believe this issue is closed and good to go, see exported initialized network files

**Comment by UICS578** [comment]
I've sent a couple of e-mails that garnered no response. Wondering if they are being blocked by mail filters at UofI? Did any of you see this e-mail from me?

All

I've expanded on Ben's code to include a "-o" parameter for runner.py. This specifies the name of the file to write out epoch#, costs, and accuracy data into. Note: this will only record the data that is marked as monitor_x = True in the SGD params.

e.g.

               monitor_evaluation_accuracy=True,
                monitor_evaluation_cost=True,
                monitor_training_accuracy=True,
                monitor_training_cost=True,

will record the epoch# and four values into the csv as all four are set as monitor = True

I'm starting runner.py with the following parameters (-r MaxFixed -e 5 -t DefaultWeightInitializer -o scott.csv) to output to csv.
I had previously used the '-i' param to runner.py to generate five random weight files and placed those in the data directory

        DefaultWeightNetwork1.json 
        DefaultWeightNetwork2.json 
        DefaultWeightNetwork3.json
        DefaultWeightNetwork4.json 
        DefaultWeightNetwork5.json
       
We still need to test that we can load all the network weights and biases from these files using the '-f' parameter to runner.py.

Does someone have time to get the latest code and check the functionality? I think we are close to doing the runs and gathering data for the write-up.

Scott

**Comment by dnhandy** [comment]
Sorry been a busy weekend. I need to commit a couple changes that fix a
divide by zero error, then I'm just going to bash script to run all 5
import files on all 4 regularizations.

**Comment by WebCandyLLC** [comment]
Ill give it a try on Max setting tonight to check the second half of the
functionality.

One notes on the options. -i and -t are used to produce the initial
networks and export them. They are independent of the rest of the options
which are used when we go to run the network from file.

**Comment by UICS578** [comment]
Completely understand busy week.

So I guess my e-mails are coming through then? I had a server problem the last two weeks so I just want to make sure it is working again.

SJ

**Comment by dnhandy** [comment]
I figured that out from the quite useful -h option. Thanks for populating
all of that to make it straight forward

**Comment by dnhandy** [comment]
Yup. Coming through

**Comment by UICS578** [comment]
great. thanks for verifying..
